### ISSUE TITLE
Dataset availability

### ISSUE THREAD

**Issue by yongen9696** [yao0510/Shot-Influence#1]
Hi,

I am wondering is there any parts of the dataset that are open to the public?

**Comment by wywyWang** [comment]
Hi,

Thanks for the interest in our work. 
We provide [two rallies](https://github.com/wywyWang/Shot-Influence/blob/main/case_study.csv) for case studies in this repo. We are also plan to release partial dataset in [ShuttleNet repo](https://github.com/wywyWang/ShuttleNet).

**Comment by yongen9696** [comment]
> We provide [two rallies](https://github.com/wywyWang/Shot-Influence/blob/main/case_study.csv) for case studies in this repo. 

May I know the column, **_aroundhead_** is empty due to what reason? and if possible, could you explain more about how is it obtained? 
Thank you!

> We are also plan to release partial dataset in [ShuttleNet repo](https://github.com/wywyWang/ShuttleNet).

Great to hear this. Thanks!

**Comment by wywyWang** [comment]
Hi,

**aroundhead** means the player hits the shot around-the-head. You can refer to [this video](https://youtu.be/BDLzp_pYcDM) for more details since it is too hard to explain in words. All of the dataset was manually labeled by domain experts.

If you have any questions, please feel free to ask me. Thanks for the interest again :)!

**Comment by wywyWang** [comment]
P.S. In men's singles, hit around-the-head is not quite common than women's singles. It will be 1 if the shot is hit around-the-head.

**Comment by yongen9696** [comment]
Great, thanks for the clarification!

Last question before closing this issue. In the paper:
> We use one of the players (denoted as Player B, and his opponents, denoted as Player A) in our dataset as the target player to predict his rally performances. Specifically, his winning rallies are labeled as positive, while the remaining losing rallies are labeled as negative.

Are the dataset limited to only 2 of the same male players?

**Comment by wywyWang** [comment]
> Are the dataset limited to only 2 of the same male players?

No, his opponents are not the same player. For example, the target player denoted as Player B may encounter C, D, E. These three players are denoted as Player A in our paper, which is *his opponents*.

**Comment by yongen9696** [comment]
> For example, the target player denoted as Player B may encounter C, D, E. These three players are denoted as Player A in our paper, which is his opponents.

If I understand it right, this _target player_ is always Player B? What are the criteria in selecting this _target player_? Would it affects your Bi- GRU if the whole dataset does not follow such order?

Another question, how do you guys handle the different lengths of rallies in your Bi-GRU. Maybe, I miss out on the paper, perhaps could you point out if it is written in the paper?

**Comment by wywyWang** [comment]
> If I understand it right, this target player is always Player B?

Yes.

> What are the criteria in selecting this target player?

We collected the matches based on the specific player due to the cooperation. We have more matches now and the extended paper is under review now.

> Would it affects your Bi- GRU if the whole dataset does not follow such order?

Sorry, I am not sure the meaning of this.

> how do you guys handle the different lengths of rallies in your Bi-GRU

We pad all sequences to the max sequence length with zeros.

**Comment by yongen9696** [comment]
Hi, sorry for the late response.

> Would it affects your Bi- GRU if the whole dataset does not follow such order?
> 
> Sorry, I am not sure the meaning of this.

Let's say Player B does not stick to a specific player like what has been done in this published paper, would the Bi-GRU still perform with the same accuracy?

**Comment by wywyWang** [comment]
Hi, sorry for the late reply.

> Would the Bi-GRU still perform with the same accuracy?

Yes, according our extended results.

BTW, we have released one match as the public dataset. You can refer in [ShuttleNet/data/](https://github.com/wywyWang/ShuttleNet/tree/master/data)

**Comment by yongen9696** [comment]
> BTW, we have released one match as the public dataset. You can refer in [ShuttleNet/data/](https://github.com/wywyWang/ShuttleNet/tree/master/data)

whoa impressive. let me look into it, thanks!
